[tool.poetry]
name = "aiontai"
version = "0.1.0"
description = "Async wrapper for nhentai API"
authors = ["LEv145"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.8.1"
schema = "^0.7.5"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
ignore_missing_imports = true
strict_optional = true
implicit_reexport = true
warn_unused_ignores = false
disallow_any_generics = false
